---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: minecraft
  name: minecraft
  namespace: minecraft
spec:
  ports:
  - port: 8123
    protocol: TCP
    name: map
  - port: 8080
    protocol: TCP
    name: console
  selector:
    app: minecraft
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: minecraft
  name: minecraft
  namespace: minecraft
spec:
  revisionHistoryLimit: 1
  selector:
    matchLabels:
      app: minecraft
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: minecraft
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: beta.kubernetes.io/arch
                operator: In
                values:
                - amd64
      initContainers:
      - name: copy-bin
        image: archifleks/spigot:1.15.2
        command: ['sh', '-c', "cp --force /spigot/* /data"]
        volumeMounts:
        - mountPath: /data
          name: minecraft-data
      containers:
      - env:
        - name: JAVA_OPTIONS
          value: "-Xms8G -Xmx8G"
        image: archifleks/spigot:1.15.2
        imagePullPolicy: Always
        name: minecraft
        ports:
        - containerPort: 25565
          hostPort: 25565
          protocol: TCP
          name: minecraft
        - containerPort: 8080
          protocol: TCP
          name: console
        - containerPort: 8123
          protocol: TCP
          name: map
        resources:
          limits:
            cpu: 2
            memory: 8Gi
          requests:
            cpu: 2
            memory: 8Gi
        volumeMounts:
        - mountPath: /spigot
          name: minecraft-data
      volumes:
      - hostPath:
          path: /srv/configs/minecraft
        name: minecraft-data
---
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: nginx
    cert-manager.io/cluster-issuer: letsencrypt
    kubernetes.io/tls-acme: "true"
  name: minecraft
  namespace: minecraft
spec:
  rules:
  - host: minecraft.archifleks.xyz
    http:
      paths:
      - backend:
          serviceName: minecraft
          servicePort: 8123
  tls:
  - hosts:
    - minecraft.archifleks.xyz
    secretName: minecraft.archifleks.xyz-cert
