apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: network-forwarder
  name: network-forwarder
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: network-forwarder
  strategy: {}
  template:
    metadata:
      labels:
        app: network-forwarder
    spec:
      containers:
      - image: alpine
        name: alpine
        command:
          - cat
        stdin: true
        tty: true
      hostNetwork: true
