apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: vault
  namespace: vault
spec:
  releaseName: vault
  chart:
    git: https://github.com/hashicorp/vault-helm
    ref: v0.5.0
    path: .
