apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: oauth2-proxy
  namespace: oauth2-proxy
spec:
  releaseName: oauth2-proxy
  chart:
    repository: https://kubernetes-charts.storage.googleapis.com
    version: 3.2.2
    name: oauth2-proxy
  values:
    config:
      existingSecret: oauth2-credentials
    extraArgs:
      provider: github
      cookie-domain: ".archifleks.xyz"
      whitelist-domain: ".archifleks.xyz"
    ingress:
      enabled: true
      path: /oauth2
      annotations:
        kubernetes.io/ingress.class: nginx
        cert-manager.io/cluster-issuer: letsencrypt
        kubernetes.io/tls-acme: "true"
      hosts:
        - auth.archifleks.xyz
      tls:
      - hosts:
        - auth.archifleks.xyz
        secretName: auth.archifleks.xyz-cert
