apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: plex
  name: plex
  namespace: seed
spec:
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      app: plex
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: plex
    spec:
      initContainers:
      - name: init-plex
        image: alpine:3.14
        command: ['sh', '-c', 'rm -rf /config/Library/Application Support/Plex Media
            Server/plexmediaserver.pid']
        volumeMounts:
        - mountPath: /config
          name: config
      containers:
      - image: linuxserver/plex:1.32.5
        imagePullPolicy: Always
        name: plex
        env:
        - name: PGID
          value: "1000"
        - name: PUID
          value: "1000"
        - name: TZ
          value: Europe/Paris
        - name: UMASK
          value: "002"
        ports:
        - containerPort: 32400
          protocol: TCP
          hostPort: 32400
        - containerPort: 32400
          protocol: UDP
          hostPort: 32400
        volumeMounts:
        - mountPath: /config
          name: config
        - mountPath: /library
          name: seed
        - mountPath: /tmp
          name: tmp
      securityContext:
        fsGroup: 1000
      volumes:
      - name: seed
        hostPath:
          # directory location on host
          path: /srv/hostpaths/seed
          # this field is optional
          type: DirectoryOrCreate
      - name: config
        hostPath:
          # directory location on host
          path: /srv/hostpaths/plex
          # this field is optional
          type: DirectoryOrCreate
      - name: tmp
        emptyDir: {}
