---
apiVersion: v1
kind: Service
metadata:
  namespace: seedbox
  name: transmission
spec:
  ports:
  - name: admin
    port: 9091
    protocol: TCP
  selector:
    app: transmission
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    flux.weave.works/automated: "true"
    flux.weave.works/tag.transmission: glob:amd64-*
  labels:
    app: transmission
  name: transmission
  namespace: seedbox
spec:
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      app: transmission
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: transmission
    spec:
      containers:
      - name: transmission
        image: linuxserver/transmission:amd64-3.00-r0-ls74
        imagePullPolicy: Always
        ports:
        - containerPort: 51413
          hostPort: 51413
          protocol: TCP
        - containerPort: 51413
          hostPort: 51413
          protocol: UDP
        volumeMounts:
        - mountPath: /downloads
          name: downloads
        - mountPath: /config
          name: config
        env:
        - name: PGID
          value: "977"
        - name: PUID
          value: "977"
        - name: TZ
          value: Europe/Paris
      securityContext:
        fsGroup: 977
      volumes:
      - name: downloads
        hostPath:
          path: /srv/seedbox
      - name: config
        hostPath:
          path: /srv/configs/transmission
---
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  namespace: seedbox
  name: torrents
  annotations:
    kubernetes.io/ingress.class: nginx
    cert-manager.io/cluster-issuer: letsencrypt
    kubernetes.io/tls-acme: "true"
    nginx.ingress.kubernetes.io/auth-url: "https://auth.archifleks.xyz/oauth2/auth"
    nginx.ingress.kubernetes.io/auth-signin: "https://auth.archifleks.xyz/oauth2/start?rd=https://$host$uri"
spec:
  rules:
  - host: torrents.archifleks.xyz
    http:
      paths:
      - backend:
          serviceName: transmission
          servicePort: 9091
  tls:
  - hosts:
    - torrents.archifleks.xyz
    secretName: torrents.archifleks.xyz-cert
