apiVersion: kibana.k8s.elastic.co/v1
kind: Kibana
metadata:
  name: kibana
  namespace: elastic-system
spec:
  version: 7.8.0
  count: 1
  http:
   tls:
     selfSignedCertificate:
       disabled: true
  elasticsearchRef:
    name: elastic
    namespace: elastic-system
---
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: nginx
    cert-manager.io/cluster-issuer: letsencrypt
    kubernetes.io/tls-acme: "true"
  name: kibana
  namespace: elastic-system
spec:
  rules:
  - host: kibana.archifleks.xyz
    http:
      paths:
      - backend:
          serviceName: kibana-kb-http
          servicePort: 5601
  tls:
  - hosts:
    - kibana.archifleks.xyz
    secretName: kibana.archifleks.xyz-cert
