apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt
spec:
  acme:
    email: lefevre.kevin@gmail.com
    server: https://acme-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
      name: acme-account-key
    solvers:
    - dns01:
        route53:
          region: eu-west-3
          accessKeyID: AKIASLDLA3PKCNHDUKZX
          secretAccessKeySecretRef:
            name: route53-credentials
            key: AWS_SECRET_ACCESS_KEY
