git:
  pollInterval: 1m
  url: ssh://git@github.com/archifleks/gitops.git
  branch: master
  path: ocelot.archifleks.xyz/resources
syncGarbageCollection:
  enabled: true
registry:
  automationInterval: "60m"
